name: Selenium Tests
on: [push]

jobs:
  test:
    runs-on: bp-ubuntu-latest-x64-2x
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run tests
        run: python -m xmlrunner discover -s tests

      - name: Upload test results to BuildPulse

        # BuildPulse is most useful when tests FAILED, so run on red builds too.

        if: always()

        uses: BuildPulseLLC/test-reporter-action@v3

        with:

          api-token: ${{ secrets.BUILDPULSE_API_TOKEN }}

          path: .
